### ISSUE TITLE
Incorrect alt text and title for LGPE origin mark in Pokemon entry

### ISSUE THREAD

**Issue by FlitPix** [Azekthi/Ribbons.Guide#70]
The alt text and title for the LGPE origin mark in a Pokemon entry are incorrectly set to "Let".

Using inspect element, the image's properties look like this when set to Let's Go! Eevee: `alt="Let" s="" go,="" eevee!'="" title="Let"`
The same is true for Let's Go! Pikachu, simply replace the empty `eevee!'` property with `pikachu!'`.

![image](https://github.com/Azekthi/Ribbons.Guide/assets/8645405/f21dc7ed-4938-4a8b-8990-512b2becc9c3)

It seems the single quote used as an apostrophe in the game title is causing issues when setting the alt text and title.

**Comment by Azekthi** [comment]
Thank you so much for the heads up, I hadn't realized I was missing so many escape sequences. Pokemon with apostrophes in their names were also breaking the move/edit/delete icon titles. Now I know better 😅
